/* COMMANDS DATABASE */
/* Fastfetch section */
const fastfetch = [
    " ",
    "",
    "                   -`                   phantekzy@archlinux",
    "                  .o+`                  -------------------------------",
    "                 `ooo/                  Full Name : Maini Lotfi Abdelkader",
    "                `+oooo:                 Alias     : phantekzy",
    "               `+oooooo:                Location  : Bir Mourad Raïs, Algiers, Algeria",
    "               -+oooooo+:               Age       : 29 (born 1996-09-08)",
    "             `/:-:++oooo+:              Role      : Elden Lord + Full Stack Dev ",
    "            `/++++/+++++++:             Status    : Looking for a job",
    "           `/++++++++++++++:            WM        : Hyprland",
    "          `/+++ooooooooooooo/`          Shell     : Zsh + Starship",
    "         ./ooosssso++osssssso+`         Editor    : Neovim (Lua)",
    "        .oossssso-````/ossssss+`        Terminal  : Alacritty",
    "       -osssssso.      :ssssssso.       Browser   : Firefox / W3M",
    "      :osssssss/        osssso+++.      Theme     : NerdFont + Gruvbox Dark",
    "     /ossssssss/        +ssssooo/-      Hobby     : CyberSecurity, low-level code",
    "   `/ossssso+/:-        -:/+osssso+-    Fun Fact  : I wear glasses because i can't C#",
    '  `+sso+:-`                 `.-/+oso:   Motto     : "Learn. Build. Play Dark Souls. Repeat."',
    " `++:.                           `-/+/",
    " .`                                 ",
    "",
    " ",
    " ",
];

/* Whoami command */
const whoami = [
    " ",
    "─────────────────────[ WHOAMI ]─────────────────────",
    " My name is Maini Lotfi Abdelkader, known online as phantekzy.",
    " I'm a junior full stack developer and a fully self-taught programmer",
    " who started from nothing and kept fighting no matter how hard life hit.",
    " ",
    "─────────────────────[ BACKSTORY ]───────────────────",
    " I was originally studying civil engineering before severe tinnitus changed",
    " everything. The nonstop noise destroyed my focus, my studies, and my life",
    " for a long time, but I refused to give up. I learned the hard way that no one",
    " is coming to save you — you either stand up or stay down forever.",
    " ",
    " So I stood up.",
    " ",
    " I earned a technical degree in web development, but the formation was",
    " terrible. I had to relearn everything on my own from scratch: YouTube,",
    " documentation, breaking things, fixing things, trying again. Learning alone",
    " feels like being dropped into a huge ocean with no map, but I kept swimming.",
    " ",
    "─────────────────────[ TECH STACK ]──────────────────",
    " Today I work with HTML, CSS, JavaScript, TypeScript, PHP, React, Node.js,",
    " TailwindCSS, MySQL, and I write all my code inside Neovim like a real dev.",
    " I love learning, but I still feel like it's never enough, and yes  I still",
    " get lost sometimes. But quitting is not even an option.",
    " ",
    "─────────────────────[ EXPERIENCE ]──────────────────",
    " I have no job experience yet, not because I'm not ready, but because every",
    " company wants experience before they even give you a chance. It's a stupid",
    " loop, but I'm breaking it my own way: improving every day and refusing to fold.",
    " ",
    "─────────────────────[ GOALS ]──────────────────────",
    " My long-term goal is to master full stack development so I can move into",
    " cybersecurity — my dream field. Certifications cost money, so first I need",
    " to earn it through code, skill, and pure determination.",
    " ",
    " I don't want regrets. I want to become one of the best, even if it's only",
    " for one day. That one day is enough for me.",
    " ",
    "─────────────────────────────────────────────────────",
    " ",
    " Type 'contact' if you want to reach me | Type 'projects' to see what I’ve built so far.",
    " ",
];

const skills = [
    " ",
    "Full Stack Development Skills:",
    "------------------------------",
    "  Frontend:",
    "  ---------",
    "    - HTML5, CSS3, TailwindCSS",
    "    - JavaScript (ES6+), TypeScript",
    "    - React, React Hooks, React Router",
    "    - Responsive & accessible design",
    "",
    "  Backend:",
    "  --------",
    "    - Node.js, Express.js",
    "    - PHP, RESTful APIs",
    "    - MySQL, Database design & queries",
    "",
    "  Tools & Workflow:",
    "  -----------------",
    "    - Git & GitHub for version control",
    "    - Neovim (Lua) for coding",
    "    - Terminal navigation & shell scripting",
    "    - Linux development environment (ArchLinux)",
    "",
    "  Soft Skills:",
    "  ------------",
    "    - Problem solving & debugging",
    "    - Self-taught, independent learner",
    "    - Project planning & execution",
    "    - Resilience under pressure",
    " ",
    "Always learning, always building, always improving.",
    " ",
];

/* Contact command */
const contact = [
    " ",
    "┌──────────────────────────────────────────────┐",
    "│                 CONTACT INFO                 │",
    "└──────────────────────────────────────────────┘",
    "",
    "Type the number to open the link :",
    "",
    "1. Email       | mainilotfi@gmail.com",
    "2. GitHub      | github.com/phantekzy",
    "3. LinkedIn    | linkedin.com/in/maini-lotfi",
    "4. X (Twitter) | @themainilotfi",
    "",
    "--------------------------------------------------",
];


/* About command */
const about = [
    " ",
    "------------------------------------------------------------------------",
    "I am Maini Lotfi Abdelkader (phantekzy), a self-taught,",
    "junior Full Stack Developer specializing in building modern,",
    "efficient, and scalable web applications.",
    "-------------------------------------------------------------------------",
    "                              Tech Stack ",
    "-------------------------------------------------------------------------",
    "  - Frontend | HTML5, CSS3, JavaScript, TypeScript, React, TailwindCSS",
    "  - Backend  | Node.js, PHP, MySQL",
    "  - Tools    | Git, GitHub, Neovim, Terminal-based workflows",
    "-------------------------------------------------------------------------",
    "",
    "                            Professional Focus",
    "-------------------------------------------------------------------------",
    "  - Writing clean, maintainable, and modular code",
    "  - Learning advanced web development patterns and best practices",
    "  - Exploring cybersecurity and low-level programming as future goals",
    "--------------------------------------------------------------------------",
    "",
    "                             Work Philosophy:",
    "--------------------------------------------------------------------------",
    "  - I thrive on challenges and continuous self-improvement",
    "  - Problem-solving with creativity and technical precision",
    "  - Building projects from scratch and iterating to improve them",
    "--------------------------------------------------------------------------",
    "                              Personal Motto:",
    "--------------------------------------------------------------------------",
    "  'Learn. Build. Play Dark Souls. Repeat.'",
    "--------------------------------------------------------------------------",
    "                              Current Objective:",
    "--------------------------------------------------------------------------",
    "  - Master Full Stack Development and gain professional experience",
    "  - Eventually transition into Cybersecurity",
    "--------------------------------------------------------------------------",
    "       Type 'projects' to see my work or 'contact' to reach out.",
    " ",
];

/* Resume command */
const resume = [
    "[phantekzy@archlinux ~]$ resume",
    " ",
    "========================================",
    "             R E S U M E",
    "========================================",
    " ",
    "Options:",
    "   [1] View Resume (opens in browser)",
    "   [2] Download Resume (PDF)",
    " ",
    "Type 1 or 2 to select an option"
];

/* Help command */
const help = [
    " ",
    "Available commands:",
    "------------------------------------------------",
    "System:",
    "------------------------------------------------",
    "  help       |  Show this help menu",
    "  clear      |  Clear the terminal screen",
    "  whoami     |  Display user identity",
    "  fastfetch  |  Display system information",
    "  exit       |  Close the terminal",
    "------------------------------------------------",
    "Profile:",
    "------------------------------------------------",
    "  about      |  Short biography and background",
    "  skills     |  List technical skills and tools",
    "  projects   |  Show featured development projects",
    "  resume     |  Display a brief CV summary",
    "  contact    |  Show contact information",
    "------------------------------------------------",
];

/* Export section */
export { fastfetch, whoami, skills, contact, resume, help, about };
